version: '3'

services:
    nc-base-image-with-qemu:
        build:
            context: .
            dockerfile: Dockerfile.qemu
            args:
                base_image: ${NC_BASE_IMAGE}
        image: ${NC_BASE_IMAGE}-qemu
        command: "echo 'base image'"
        labels:
        - "traefik.enable=false"
    mysql:
        image: ${MYSQL_IMAGE}
        restart: unless-stopped
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        labels:
        - "traefik.enable=false"
    nextcloud-rpi:
        build:
            context: ./14.0/apache
            dockerfile: Dockerfile
            args:
                base_image: ${NC_BASE_IMAGE}-qemu
        image: ${IMAGE_NAME}
        restart: unless-stopped
        depends_on:
            - nc-base-image-with-qemu
            - mysql
        environment:
            NEXTCLOUD_DATA_DIR: /var/www/html/data
            MYSQL_HOST: mysql
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${NC_DATA}:/var/www/html/data
        labels:
        - "traefik.enable=true"
        - "traefik.frontend.rule=PathPrefixStrip:/nextcloud;"

volumes:
    nc_data:
    mysql_data:
