version: '3'

services:
    nc-base-image-with-qemu:
        build:
            context: .
            dockerfile: Dockerfile.qemu
            args:
                base_image: ${NC_BASE_IMAGE}
        image: ${NC_BASE_IMAGE}-qemu
    mysql:
        image: ${MYSQL_IMAGE}
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - mysql_data:/var/lib/mysql
    nextcloud-docker-pi:
        build:
            context: ./14.0/apache
            dockerfile: Dockerfile
            args:
                base_image: ${NC_BASE_IMAGE}-qemu
        image: ${IMAGE_NAME}
        depends_on:
            - nc-base-image-with-qemu
            - mysql
        environment:
            NEXTCLOUD_DATA_DIR: /var/www/html/data
            MYSQL_HOST: mysql
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - nc_data:/var/www/html/data
        ports:
        - "80:80"
        - "443:443"
        - "4443:4443"

volumes:
    nc_data:
    mysql_data:
