version: '3'

services:
    mysql:
        image: ${MYSQL_IMAGE}
        restart: on-failure
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${MYSQL_DATA}:/var/lib/mysql
        labels:
            - "traefik.enable=false"
    nextcloud-rpi:
        image: ${IMAGE_NAME}:${IMAGE_TAG}
        restart: on-failure
        depends_on:
            - mysql
        environment:
            NEXTCLOUD_DATA_DIR: /var/www/html/data
            MYSQL_HOST: mysql
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes:
            - ${NC_HTML_DATA}:/var/www/html
            - ${NC_DATA}:/var/www/html/data
        labels:
            - "traefik.enable=true"
            - "traefik.frontend.rule=PathPrefixStrip:/nextcloud;"

volumes:
    nc_data:
    mysql_data:
